[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "usf-class-picker"
version = "0.1.0"
description = "Package for picking USF classes"
authors = [{name = "Will"}]
dependencies = [
  "httpx>=0.27",
  "PySide6>=6.6",
  "apscheduler>=3.10",
]

[project.optional-dependencies]
dev = ["pytest>=8.0", "ruff>=0.5"]
